// <auto-generated />
namespace DYF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.9.9")]
    public sealed partial class AddOneToManyRelationBetween_Bande_VenteOeuf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOneToManyRelationBetween_Bande_VenteOeuf));
        
        string IMigrationMetadata.Id
        {
            get { return "201708061832211_AddOneToManyRelationBetween_Bande_VenteOeuf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
