// <auto-generated />
namespace DYF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.9.9")]
    public sealed partial class Removing_field_ecarty_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removing_field_ecarty_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171012034_Removing_field_ecarty_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
